### ISSUE TITLE
link to tx_news records in header_field throw error

### ISSUE THREAD

**Issue by nabossha** [TYPO3-Headless/headless#527] opened 2022-12-14 12:07 UTC
**TYPO3:** 11.5.19 / 11.5.20
**EXT:headless:**  v3.2.2

<br class="Apple-interchange-newline">

when linking to a news-record in the header-field of a content element (or linking a sys_file_reference), the following error is thrown:
![tx_news-error](https://user-images.githubusercontent.com/3851681/207589225-bb7205a4-cee0-4861-b479-94e0cbf6bd8e.png)

**observation:**
linking to pages, a file-record or external URL in the header-field works as expected. As you can see below, and links to news-records are parsed correctly when added in the bodytext using the RTE:

![headerlink](https://user-images.githubusercontent.com/3851681/207589426-a4d6eaa3-16dd-48e1-bb09-b481aa5ea262.png)

value of the header_link for tx_news is as follows and identical to the correctly parsed link within the bodytext
`t3://record?identifier=news&uid=894`

**temporary workaround** 
when appliying
`lib.contentElementWithHeader.fields.content.field.headerLink.typolink.returnLast = url`
linked news_records from the field header_link are parsed correctly but the same problem then occurs with record-links from a sys_file_reference since returnLast = result is hardcoded in https://github.com/TYPO3-Headless/headless/blob/master/Classes/Utility/FileUtility.php#L95

![sys_file_reference](https://user-images.githubusercontent.com/3851681/207591282-4e383467-df3c-4ecb-a289-2bd2f11124f5.png)

is there any relation to https://github.com/TYPO3-Headless/headless/issues/462 ..? 

**used linkhandler-configuration:**
```
config.recordLinks.news {
    typolink {
        parameter = 19
        additionalParams.data = field:uid
        additionalParams.wrap = &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]=|
    }
}
```

**Comment by twoldanski** [comment] 2023-03-08 08:17
@nabossha thank you for detailed report. I'm closing issue, because root cause is in core, not in ext:headless, please see https://forge.typo3.org/issues/100106

**Closed by twoldanski** 2023-03-08 08:17 UTC
